INFO 2025-08-08 15:16:51,264 autoreload 112701 139941649666112 Watching for file changes with StatReloader
ERROR 2025-08-08 15:17:07,509 log 112701 139941587707584 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/oapi_canteen/urls.py", line 12, in <lambda>
    path('', lambda request: redirect('dashboard:home')),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
WARNING 2025-08-08 15:17:07,965 log 112701 139941587707584 Not Found: /favicon.ico
ERROR 2025-08-08 15:17:19,754 log 112701 139941587707584 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/oapi_canteen/urls.py", line 12, in <lambda>
    path('', lambda request: redirect('dashboard:home')),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
INFO 2025-08-08 15:17:44,468 autoreload 112770 140450232750144 Watching for file changes with StatReloader
ERROR 2025-08-08 15:18:14,117 log 112770 140450172233408 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/oapi_canteen/urls.py", line 12, in <lambda>
    path('', lambda request: redirect('dashboard:home')),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
ERROR 2025-08-08 15:18:38,660 log 112770 140450172233408 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/context.py", line 251, in bind_template
    processors = template.engine.template_context_processors + self._processors
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 118, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 118, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apps.notifications.context_processors'
INFO 2025-08-08 18:10:30,046 autoreload 117968 140258559311936 Watching for file changes with StatReloader
ERROR 2025-08-08 18:10:35,264 log 117968 140258497517248 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/oapi_canteen/urls.py", line 12, in <lambda>
    path('', lambda request: redirect('dashboard:home')),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
WARNING 2025-08-08 18:10:35,490 log 117968 140258497517248 Not Found: /favicon.ico
INFO 2025-08-08 18:16:05,720 autoreload 117968 140258559311936 /home/codex/oapi_canteen/apps/orders/models.py changed, reloading.
INFO 2025-08-08 18:16:06,800 autoreload 118680 140454697971776 Watching for file changes with StatReloader
INFO 2025-08-08 18:16:26,338 autoreload 118680 140454697971776 /home/codex/oapi_canteen/apps/orders/models.py changed, reloading.
INFO 2025-08-08 18:16:27,471 autoreload 118685 140431724171328 Watching for file changes with StatReloader
INFO 2025-08-08 18:16:31,459 autoreload 118685 140431724171328 /home/codex/oapi_canteen/apps/orders/admin.py changed, reloading.
INFO 2025-08-08 18:16:32,516 autoreload 118692 140098694332480 Watching for file changes with StatReloader
INFO 2025-08-08 18:19:06,455 autoreload 118692 140098694332480 /home/codex/oapi_canteen/apps/dashboard/urls.py changed, reloading.
INFO 2025-08-08 18:19:07,354 autoreload 118842 140246194409536 Watching for file changes with StatReloader
INFO 2025-08-08 18:19:29,705 autoreload 118855 140549485744192 Watching for file changes with StatReloader
INFO 2025-08-08 19:17:18,106 autoreload 164096 140197733486656 Watching for file changes with StatReloader
WARNING 2025-08-08 19:17:46,427 log 164096 140197597542080 Not Found: /accounts/login/
WARNING 2025-08-08 19:17:46,567 log 164096 140197597542080 Not Found: /favicon.ico
WARNING 2025-08-08 19:18:07,975 log 164096 140197597542080 Not Found: /accounts/login/
ERROR 2025-08-08 19:18:22,840 log 164096 140197597542080 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/context.py", line 251, in bind_template
    processors = template.engine.template_context_processors + self._processors
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 118, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 118, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apps.notifications.context_processors'
INFO 2025-08-08 19:18:56,910 autoreload 185176 140133649928256 Watching for file changes with StatReloader
WARNING 2025-08-08 19:19:09,642 log 185176 140133589313216 Not Found: /accounts/login/
WARNING 2025-08-08 19:21:23,115 log 185176 140133589313216 Not Found: /accounts/login/
WARNING 2025-08-08 19:21:25,497 log 185176 140133589313216 Not Found: /accounts/login/
WARNING 2025-08-08 19:21:26,794 log 185176 140133589313216 Not Found: /accounts/login/
INFO 2025-08-08 19:22:26,713 autoreload 185176 140133649928256 /home/codex/oapi_canteen/oapi_canteen/settings/base.py changed, reloading.
INFO 2025-08-08 19:23:24,034 autoreload 204509 139671498543168 Watching for file changes with StatReloader
WARNING 2025-08-08 19:23:30,874 log 204509 139671436781248 Not Found: /accounts/login/
WARNING 2025-08-08 19:43:18,697 log 204509 139671436781248 Not Found: /accounts/login/
WARNING 2025-08-08 19:43:18,841 log 204509 139671436781248 Not Found: /favicon.ico
WARNING 2025-08-08 19:43:23,771 log 204509 139671436781248 Not Found: /accounts/login/
INFO 2025-08-11 19:36:23,795 autoreload 26576 140286533386304 Watching for file changes with StatReloader
INFO 2025-08-11 19:36:42,337 basehttp 26576 140286477985472 "GET / HTTP/1.1" 302 0
INFO 2025-08-11 19:36:42,347 basehttp 26576 140286477985472 "GET /dashboard/ HTTP/1.1" 302 0
ERROR 2025-08-11 19:36:42,990 log 26576 140286477985472 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-08-11 19:36:42,996 basehttp 26576 140286477985472 "GET /auth/login/?next=/dashboard/ HTTP/1.1" 500 87601
WARNING 2025-08-11 19:36:43,097 log 26576 140286477985472 Not Found: /favicon.ico
WARNING 2025-08-11 19:36:43,099 basehttp 26576 140286477985472 "GET /favicon.ico HTTP/1.1" 404 3228
INFO 2025-08-11 19:37:05,562 basehttp 26576 140286477985472 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-08-11 19:37:05,720 basehttp 26576 140286477985472 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4161
INFO 2025-08-11 19:37:06,062 basehttp 26576 140286468544192 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
INFO 2025-08-11 19:37:06,074 basehttp 26576 140286231566016 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2025-08-11 19:37:06,078 basehttp 26576 140286477985472 "GET /static/admin/css/base.css HTTP/1.1" 200 21544
INFO 2025-08-11 19:37:06,081 basehttp 26576 140286239958720 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-08-11 19:37:06,080 basehttp 26576 140286248351424 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-08-11 19:37:06,081 basehttp 26576 140286460151488 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2025-08-11 19:37:06,084 basehttp 26576 140286468544192 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
WARNING 2025-08-11 19:37:06,306 log 26576 140286468544192 Not Found: /favicon.ico
INFO 2025-08-11 19:37:16,990 basehttp 26576 140286477985472 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4325
WARNING 2025-08-11 19:37:17,140 log 26576 140286239958720 Not Found: /favicon.ico
INFO 2025-08-11 19:38:40,119 autoreload 26779 139622276350016 Watching for file changes with StatReloader
INFO 2025-08-11 19:38:54,412 basehttp 26779 139622220818112 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-08-11 19:38:54,670 basehttp 26779 139622220818112 "GET /admin/ HTTP/1.1" 200 10029
INFO 2025-08-11 19:38:54,800 basehttp 26779 139622220818112 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-08-11 19:38:54,815 basehttp 26779 139622220818112 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-08-11 19:38:54,819 basehttp 26779 139622139033280 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-08-11 19:39:16,958 basehttp 26779 139622220818112 "GET /admin/orders/cart/ HTTP/1.1" 200 10678
INFO 2025-08-11 19:39:17,064 basehttp 26779 139622122247872 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-08-11 19:39:17,086 basehttp 26779 139622113855168 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-08-11 19:39:17,091 basehttp 26779 139622139033280 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
INFO 2025-08-11 19:39:17,100 basehttp 26779 139622139033280 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-08-11 19:39:17,130 basehttp 26779 139622122247872 "GET /static/admin/js/actions.js HTTP/1.1" 200 8067
INFO 2025-08-11 19:39:17,134 basehttp 26779 139622113855168 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-08-11 19:39:17,135 basehttp 26779 139622105462464 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
INFO 2025-08-11 19:39:17,145 basehttp 26779 139622139033280 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-08-11 19:39:17,246 basehttp 26779 139622130640576 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-08-11 19:39:17,291 basehttp 26779 139622220818112 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:17,303 basehttp 26779 139622105462464 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-08-11 19:39:17,350 basehttp 26779 139622130640576 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-08-11 19:39:17,407 basehttp 26779 139622105462464 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
WARNING 2025-08-11 19:39:17,529 log 26779 139622105462464 Not Found: /favicon.ico
INFO 2025-08-11 19:39:24,768 basehttp 26779 139622130640576 "GET /admin/notifications/notification/ HTTP/1.1" 200 12807
INFO 2025-08-11 19:39:24,933 basehttp 26779 139622130640576 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:24,979 basehttp 26779 139622130640576 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-08-11 19:39:32,798 basehttp 26779 139622130640576 "GET /admin/payments/paymentmethod/ HTTP/1.1" 200 11891
INFO 2025-08-11 19:39:32,904 basehttp 26779 139622130640576 "GET /static/admin/css/forms.css HTTP/1.1" 200 9090
INFO 2025-08-11 19:39:32,997 basehttp 26779 139622130640576 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
INFO 2025-08-11 19:39:33,039 basehttp 26779 139622122247872 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:36,597 basehttp 26779 139622130640576 "GET /admin/payments/paymentmethod/?provider__exact=ORANGE HTTP/1.1" 200 12122
INFO 2025-08-11 19:39:36,846 basehttp 26779 139622130640576 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:39,676 basehttp 26779 139622130640576 "GET /admin/payments/paymentmethod/?provider__exact=MTN HTTP/1.1" 200 12107
INFO 2025-08-11 19:39:39,877 basehttp 26779 139622130640576 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:41,596 basehttp 26779 139622130640576 "GET /admin/payments/paymentmethod/?provider__exact=CASH HTTP/1.1" 200 12112
INFO 2025-08-11 19:39:41,846 basehttp 26779 139622130640576 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
WARNING 2025-08-11 19:39:42,061 log 26779 139622130640576 Not Found: /favicon.ico
