INFO 2025-08-08 15:16:51,264 autoreload 112701 139941649666112 Watching for file changes with StatReloader
ERROR 2025-08-08 15:17:07,509 log 112701 139941587707584 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/oapi_canteen/urls.py", line 12, in <lambda>
    path('', lambda request: redirect('dashboard:home')),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
WARNING 2025-08-08 15:17:07,965 log 112701 139941587707584 Not Found: /favicon.ico
ERROR 2025-08-08 15:17:19,754 log 112701 139941587707584 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/oapi_canteen/urls.py", line 12, in <lambda>
    path('', lambda request: redirect('dashboard:home')),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
INFO 2025-08-08 15:17:44,468 autoreload 112770 140450232750144 Watching for file changes with StatReloader
ERROR 2025-08-08 15:18:14,117 log 112770 140450172233408 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/oapi_canteen/urls.py", line 12, in <lambda>
    path('', lambda request: redirect('dashboard:home')),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
ERROR 2025-08-08 15:18:38,660 log 112770 140450172233408 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/context.py", line 251, in bind_template
    processors = template.engine.template_context_processors + self._processors
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 118, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 118, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apps.notifications.context_processors'
INFO 2025-08-08 18:10:30,046 autoreload 117968 140258559311936 Watching for file changes with StatReloader
ERROR 2025-08-08 18:10:35,264 log 117968 140258497517248 Internal Server Error: /
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/oapi_canteen/urls.py", line 12, in <lambda>
    path('', lambda request: redirect('dashboard:home')),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
WARNING 2025-08-08 18:10:35,490 log 117968 140258497517248 Not Found: /favicon.ico
INFO 2025-08-08 18:16:05,720 autoreload 117968 140258559311936 /home/codex/oapi_canteen/apps/orders/models.py changed, reloading.
INFO 2025-08-08 18:16:06,800 autoreload 118680 140454697971776 Watching for file changes with StatReloader
INFO 2025-08-08 18:16:26,338 autoreload 118680 140454697971776 /home/codex/oapi_canteen/apps/orders/models.py changed, reloading.
INFO 2025-08-08 18:16:27,471 autoreload 118685 140431724171328 Watching for file changes with StatReloader
INFO 2025-08-08 18:16:31,459 autoreload 118685 140431724171328 /home/codex/oapi_canteen/apps/orders/admin.py changed, reloading.
INFO 2025-08-08 18:16:32,516 autoreload 118692 140098694332480 Watching for file changes with StatReloader
INFO 2025-08-08 18:19:06,455 autoreload 118692 140098694332480 /home/codex/oapi_canteen/apps/dashboard/urls.py changed, reloading.
INFO 2025-08-08 18:19:07,354 autoreload 118842 140246194409536 Watching for file changes with StatReloader
INFO 2025-08-08 18:19:29,705 autoreload 118855 140549485744192 Watching for file changes with StatReloader
INFO 2025-08-08 19:17:18,106 autoreload 164096 140197733486656 Watching for file changes with StatReloader
WARNING 2025-08-08 19:17:46,427 log 164096 140197597542080 Not Found: /accounts/login/
WARNING 2025-08-08 19:17:46,567 log 164096 140197597542080 Not Found: /favicon.ico
WARNING 2025-08-08 19:18:07,975 log 164096 140197597542080 Not Found: /accounts/login/
ERROR 2025-08-08 19:18:22,840 log 164096 140197597542080 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/context.py", line 251, in bind_template
    processors = template.engine.template_context_processors + self._processors
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 118, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 118, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apps.notifications.context_processors'
INFO 2025-08-08 19:18:56,910 autoreload 185176 140133649928256 Watching for file changes with StatReloader
WARNING 2025-08-08 19:19:09,642 log 185176 140133589313216 Not Found: /accounts/login/
WARNING 2025-08-08 19:21:23,115 log 185176 140133589313216 Not Found: /accounts/login/
WARNING 2025-08-08 19:21:25,497 log 185176 140133589313216 Not Found: /accounts/login/
WARNING 2025-08-08 19:21:26,794 log 185176 140133589313216 Not Found: /accounts/login/
INFO 2025-08-08 19:22:26,713 autoreload 185176 140133649928256 /home/codex/oapi_canteen/oapi_canteen/settings/base.py changed, reloading.
INFO 2025-08-08 19:23:24,034 autoreload 204509 139671498543168 Watching for file changes with StatReloader
WARNING 2025-08-08 19:23:30,874 log 204509 139671436781248 Not Found: /accounts/login/
WARNING 2025-08-08 19:43:18,697 log 204509 139671436781248 Not Found: /accounts/login/
WARNING 2025-08-08 19:43:18,841 log 204509 139671436781248 Not Found: /favicon.ico
WARNING 2025-08-08 19:43:23,771 log 204509 139671436781248 Not Found: /accounts/login/
INFO 2025-08-11 19:36:23,795 autoreload 26576 140286533386304 Watching for file changes with StatReloader
INFO 2025-08-11 19:36:42,337 basehttp 26576 140286477985472 "GET / HTTP/1.1" 302 0
INFO 2025-08-11 19:36:42,347 basehttp 26576 140286477985472 "GET /dashboard/ HTTP/1.1" 302 0
ERROR 2025-08-11 19:36:42,990 log 26576 140286477985472 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-08-11 19:36:42,996 basehttp 26576 140286477985472 "GET /auth/login/?next=/dashboard/ HTTP/1.1" 500 87601
WARNING 2025-08-11 19:36:43,097 log 26576 140286477985472 Not Found: /favicon.ico
WARNING 2025-08-11 19:36:43,099 basehttp 26576 140286477985472 "GET /favicon.ico HTTP/1.1" 404 3228
INFO 2025-08-11 19:37:05,562 basehttp 26576 140286477985472 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-08-11 19:37:05,720 basehttp 26576 140286477985472 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4161
INFO 2025-08-11 19:37:06,062 basehttp 26576 140286468544192 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
INFO 2025-08-11 19:37:06,074 basehttp 26576 140286231566016 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2025-08-11 19:37:06,078 basehttp 26576 140286477985472 "GET /static/admin/css/base.css HTTP/1.1" 200 21544
INFO 2025-08-11 19:37:06,081 basehttp 26576 140286239958720 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-08-11 19:37:06,080 basehttp 26576 140286248351424 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-08-11 19:37:06,081 basehttp 26576 140286460151488 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2025-08-11 19:37:06,084 basehttp 26576 140286468544192 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
WARNING 2025-08-11 19:37:06,306 log 26576 140286468544192 Not Found: /favicon.ico
INFO 2025-08-11 19:37:16,990 basehttp 26576 140286477985472 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4325
WARNING 2025-08-11 19:37:17,140 log 26576 140286239958720 Not Found: /favicon.ico
INFO 2025-08-11 19:38:40,119 autoreload 26779 139622276350016 Watching for file changes with StatReloader
INFO 2025-08-11 19:38:54,412 basehttp 26779 139622220818112 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-08-11 19:38:54,670 basehttp 26779 139622220818112 "GET /admin/ HTTP/1.1" 200 10029
INFO 2025-08-11 19:38:54,800 basehttp 26779 139622220818112 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-08-11 19:38:54,815 basehttp 26779 139622220818112 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-08-11 19:38:54,819 basehttp 26779 139622139033280 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-08-11 19:39:16,958 basehttp 26779 139622220818112 "GET /admin/orders/cart/ HTTP/1.1" 200 10678
INFO 2025-08-11 19:39:17,064 basehttp 26779 139622122247872 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-08-11 19:39:17,086 basehttp 26779 139622113855168 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-08-11 19:39:17,091 basehttp 26779 139622139033280 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
INFO 2025-08-11 19:39:17,100 basehttp 26779 139622139033280 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-08-11 19:39:17,130 basehttp 26779 139622122247872 "GET /static/admin/js/actions.js HTTP/1.1" 200 8067
INFO 2025-08-11 19:39:17,134 basehttp 26779 139622113855168 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-08-11 19:39:17,135 basehttp 26779 139622105462464 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
INFO 2025-08-11 19:39:17,145 basehttp 26779 139622139033280 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-08-11 19:39:17,246 basehttp 26779 139622130640576 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-08-11 19:39:17,291 basehttp 26779 139622220818112 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:17,303 basehttp 26779 139622105462464 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-08-11 19:39:17,350 basehttp 26779 139622130640576 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-08-11 19:39:17,407 basehttp 26779 139622105462464 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
WARNING 2025-08-11 19:39:17,529 log 26779 139622105462464 Not Found: /favicon.ico
INFO 2025-08-11 19:39:24,768 basehttp 26779 139622130640576 "GET /admin/notifications/notification/ HTTP/1.1" 200 12807
INFO 2025-08-11 19:39:24,933 basehttp 26779 139622130640576 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:24,979 basehttp 26779 139622130640576 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-08-11 19:39:32,798 basehttp 26779 139622130640576 "GET /admin/payments/paymentmethod/ HTTP/1.1" 200 11891
INFO 2025-08-11 19:39:32,904 basehttp 26779 139622130640576 "GET /static/admin/css/forms.css HTTP/1.1" 200 9090
INFO 2025-08-11 19:39:32,997 basehttp 26779 139622130640576 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
INFO 2025-08-11 19:39:33,039 basehttp 26779 139622122247872 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:36,597 basehttp 26779 139622130640576 "GET /admin/payments/paymentmethod/?provider__exact=ORANGE HTTP/1.1" 200 12122
INFO 2025-08-11 19:39:36,846 basehttp 26779 139622130640576 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:39,676 basehttp 26779 139622130640576 "GET /admin/payments/paymentmethod/?provider__exact=MTN HTTP/1.1" 200 12107
INFO 2025-08-11 19:39:39,877 basehttp 26779 139622130640576 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-11 19:39:41,596 basehttp 26779 139622130640576 "GET /admin/payments/paymentmethod/?provider__exact=CASH HTTP/1.1" 200 12112
INFO 2025-08-11 19:39:41,846 basehttp 26779 139622130640576 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
WARNING 2025-08-11 19:39:42,061 log 26779 139622130640576 Not Found: /favicon.ico
INFO 2025-08-12 13:31:48,110 autoreload 10566 140543380758592 Watching for file changes with StatReloader
INFO 2025-08-12 13:31:59,040 basehttp 10566 140543324579520 "GET /admin/payments/paymentmethod/?provider__exact=CASH HTTP/1.1" 302 0
INFO 2025-08-12 13:31:59,281 basehttp 10566 140543324579520 "GET /admin/login/?next=/admin/payments/paymentmethod/%3Fprovider__exact%3DCASH HTTP/1.1" 200 4253
INFO 2025-08-12 13:32:21,228 basehttp 10566 140543324579520 "POST /admin/login/?next=/admin/payments/paymentmethod/%3Fprovider__exact%3DCASH HTTP/1.1" 200 4417
INFO 2025-08-12 13:32:21,318 basehttp 10566 140543324579520 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-08-12 13:32:21,332 basehttp 10566 140543324579520 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-08-12 13:32:21,339 basehttp 10566 140543306745536 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-08-12 13:32:21,350 basehttp 10566 140543298352832 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
INFO 2025-08-12 13:32:21,351 basehttp 10566 140543289960128 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2025-08-12 13:32:21,354 basehttp 10566 140542939756224 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
INFO 2025-08-12 13:32:21,425 basehttp 10566 140543315138240 "GET /static/admin/css/base.css HTTP/1.1" 200 21544
WARNING 2025-08-12 13:32:22,022 log 10566 140543315138240 Not Found: /favicon.ico
INFO 2025-08-12 13:32:30,418 basehttp 10566 140542939756224 "POST /admin/login/?next=/admin/payments/paymentmethod/%3Fprovider__exact%3DCASH HTTP/1.1" 302 0
INFO 2025-08-12 13:32:30,965 basehttp 10566 140542939756224 "GET /admin/payments/paymentmethod/?provider__exact=CASH HTTP/1.1" 200 12112
INFO 2025-08-12 13:32:31,130 basehttp 10566 140542939756224 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-08-12 13:32:31,142 basehttp 10566 140542939756224 "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2025-08-12 13:32:31,178 basehttp 10566 140543289960128 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-08-12 13:32:31,180 basehttp 10566 140543306745536 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-08-12 13:32:31,343 basehttp 10566 140542939756224 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-08-12 13:32:31,430 basehttp 10566 140543298352832 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-12 13:32:31,446 basehttp 10566 140542939756224 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-08-12 13:32:31,488 basehttp 10566 140542939756224 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-08-12 13:32:31,528 basehttp 10566 140542939756224 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-08-12 13:32:31,532 basehttp 10566 140543298352832 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-08-12 13:32:31,590 basehttp 10566 140542939756224 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-08-12 13:32:31,616 basehttp 10566 140543298352832 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-08-12 13:32:31,694 basehttp 10566 140542939756224 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
INFO 2025-08-12 13:32:31,791 basehttp 10566 140542939756224 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-08-12 13:32:31,794 basehttp 10566 140543306745536 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-08-12 13:32:31,795 basehttp 10566 140543298352832 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
WARNING 2025-08-12 13:32:31,911 log 10566 140542939756224 Not Found: /favicon.ico
INFO 2025-08-12 13:32:44,630 basehttp 10566 140543324579520 "GET /admin/payments/paymentmethod/?_facets=True&provider__exact=CASH HTTP/1.1" 200 12296
INFO 2025-08-12 13:32:44,829 basehttp 10566 140543298352832 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-08-12 13:32:44,882 basehttp 10566 140543298352832 "GET /static/admin/img/icon-hidelink.svg HTTP/1.1" 200 784
INFO 2025-08-12 13:32:55,171 basehttp 10566 140543324579520 "GET /admin/payments/paymentmethod/?provider__exact=CASH HTTP/1.1" 200 12112
INFO 2025-08-12 13:33:02,007 basehttp 10566 140543324579520 "GET / HTTP/1.1" 302 0
INFO 2025-08-12 13:33:02,123 basehttp 10566 140543324579520 "GET /dashboard/ HTTP/1.1" 302 0
ERROR 2025-08-12 13:33:02,730 log 10566 140543324579520 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashboard/user_dashboard.html
ERROR 2025-08-12 13:33:02,732 basehttp 10566 140543324579520 "GET /dashboard/user/ HTTP/1.1" 500 87523
ERROR 2025-08-12 13:39:09,944 log 10566 140543324579520 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-08-12 13:39:09,952 basehttp 10566 140543324579520 "GET /dashboard/user/ HTTP/1.1" 500 159580
WARNING 2025-08-12 13:39:10,268 log 10566 140543324579520 Not Found: /favicon.ico
WARNING 2025-08-12 13:39:41,146 log 10566 140543324579520 Not Found: /dashboard/user_dashbord
WARNING 2025-08-12 13:39:41,148 basehttp 10566 140543324579520 "GET /dashboard/user_dashbord HTTP/1.1" 404 5057
INFO 2025-08-12 13:39:51,993 basehttp 10566 140543324579520 "GET /dashboard HTTP/1.1" 301 0
INFO 2025-08-12 13:39:52,244 basehttp 10566 140543324579520 "GET /dashboard/ HTTP/1.1" 302 0
ERROR 2025-08-12 13:39:52,354 log 10566 140543324579520 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-08-12 13:39:52,356 basehttp 10566 140543324579520 "GET /dashboard/user/ HTTP/1.1" 500 159580
INFO 2025-08-12 13:43:29,615 autoreload 10566 140543380758592 /home/codex/oapi_canteen/oapi_canteen/settings/base.py changed, reloading.
INFO 2025-08-12 13:45:22,665 autoreload 11784 140555791802432 Watching for file changes with StatReloader
INFO 2025-08-12 13:45:37,378 basehttp 11784 140555735525056 "GET /dashboard/ HTTP/1.1" 302 0
ERROR 2025-08-12 13:45:37,734 log 11784 140555735525056 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-08-12 13:45:37,743 basehttp 11784 140555735525056 "GET /dashboard/user/ HTTP/1.1" 500 159580
INFO 2025-08-12 16:52:02,254 autoreload 17681 140681061777472 Watching for file changes with StatReloader
ERROR 2025-08-12 16:52:11,291 log 17681 140681006802624 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-08-12 16:52:11,302 basehttp 17681 140681006802624 "GET /dashboard/user/ HTTP/1.1" 500 159580
WARNING 2025-08-12 16:52:12,275 log 17681 140681006802624 Not Found: /favicon.ico
INFO 2025-08-12 17:04:02,548 autoreload 18500 140431265906752 Watching for file changes with StatReloader
ERROR 2025-08-12 17:04:08,735 log 18500 140431136388800 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2025-08-12 17:04:08,739 basehttp 18500 140431136388800 "GET /dashboard/user/ HTTP/1.1" 500 135088
WARNING 2025-08-12 17:04:08,968 log 18500 140431136388800 Not Found: /favicon.ico
ERROR 2025-08-12 17:07:08,012 log 18500 140431136388800 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
ERROR 2025-08-12 17:07:08,018 basehttp 18500 140431136388800 "GET /dashboard/user/ HTTP/1.1" 500 170272
WARNING 2025-08-12 17:07:08,460 log 18500 140431136388800 Not Found: /favicon.ico
INFO 2025-08-12 17:07:31,785 autoreload 18773 140190332502080 Watching for file changes with StatReloader
ERROR 2025-08-12 17:07:36,687 log 18773 140190275331776 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
ERROR 2025-08-12 17:07:36,694 basehttp 18773 140190275331776 "GET /dashboard/user/ HTTP/1.1" 500 170272
ERROR 2025-08-12 17:09:48,719 log 18773 140190275331776 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
ERROR 2025-08-12 17:09:48,750 basehttp 18773 140190275331776 "GET /dashboard/user/ HTTP/1.1" 500 149740
WARNING 2025-08-12 17:09:49,057 log 18773 140190275331776 Not Found: /favicon.ico
ERROR 2025-08-12 18:39:46,691 log 18773 140190275331776 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
ERROR 2025-08-12 18:39:46,726 basehttp 18773 140190275331776 "GET /dashboard/user/ HTTP/1.1" 500 170274
WARNING 2025-08-12 18:39:47,161 log 18773 140190275331776 Not Found: /favicon.ico
INFO 2025-08-12 18:44:06,493 autoreload 18773 140190332502080 /home/codex/oapi_canteen/apps/accounts/urls.py changed, reloading.
INFO 2025-08-12 18:44:11,269 autoreload 23378 140055117774912 Watching for file changes with StatReloader
INFO 2025-08-12 18:44:21,870 autoreload 23378 140055117774912 /home/codex/oapi_canteen/apps/accounts/urls.py changed, reloading.
INFO 2025-08-12 18:44:23,134 autoreload 23433 140464728612928 Watching for file changes with StatReloader
INFO 2025-08-12 18:44:25,077 autoreload 23433 140464728612928 /home/codex/oapi_canteen/apps/accounts/urls.py changed, reloading.
INFO 2025-08-12 18:44:25,810 autoreload 23460 140516164313152 Watching for file changes with StatReloader
INFO 2025-08-12 18:45:26,484 autoreload 23460 140516164313152 /home/codex/oapi_canteen/apps/accounts/urls.py changed, reloading.
INFO 2025-08-12 18:45:27,306 autoreload 23513 140268709453888 Watching for file changes with StatReloader
ERROR 2025-08-12 18:46:56,767 log 23513 140268653242048 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
ERROR 2025-08-12 18:46:56,776 basehttp 23513 140268653242048 "GET /dashboard/user/ HTTP/1.1" 500 170304
WARNING 2025-08-12 18:46:57,036 log 23513 140268653242048 Not Found: /favicon.ico
INFO 2025-08-12 18:47:58,726 autoreload 23698 140232921522240 Watching for file changes with StatReloader
INFO 2025-08-12 18:48:06,081 basehttp 23698 140232865343168 "GET / HTTP/1.1" 302 0
INFO 2025-08-12 18:48:06,257 basehttp 23698 140232865343168 "GET /dashboard/ HTTP/1.1" 302 0
ERROR 2025-08-12 18:48:06,448 log 23698 140232865343168 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
ERROR 2025-08-12 18:48:06,459 basehttp 23698 140232865343168 "GET /dashboard/user/ HTTP/1.1" 500 170304
WARNING 2025-08-12 18:48:06,662 log 23698 140232865343168 Not Found: /favicon.ico
ERROR 2025-08-12 18:50:56,999 log 23698 140232865343168 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 515, in parse
    self.unclosed_block_tag(parse_until)
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 578, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 28: 'if'. Looking for one of: elif, else, endif.
ERROR 2025-08-12 18:50:57,006 basehttp 23698 140232865343168 "GET /dashboard/user/ HTTP/1.1" 500 193457
WARNING 2025-08-12 18:50:57,289 log 23698 140232865343168 Not Found: /favicon.ico
ERROR 2025-08-12 18:51:41,755 log 23698 140232865343168 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 515, in parse
    self.unclosed_block_tag(parse_until)
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 578, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 28: 'if'. Looking for one of: elif, else, endif.
ERROR 2025-08-12 18:51:41,762 basehttp 23698 140232865343168 "GET /dashboard/user/ HTTP/1.1" 500 193505
ERROR 2025-08-12 18:55:38,601 log 23698 140232865343168 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'settings' not found. 'settings' is not a valid view function or pattern name.
ERROR 2025-08-12 18:55:38,606 basehttp 23698 140232865343168 "GET /dashboard/user/ HTTP/1.1" 500 170757
WARNING 2025-08-12 18:55:38,987 log 23698 140232865343168 Not Found: /favicon.ico
ERROR 2025-08-12 19:21:38,990 log 23698 140232865343168 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
ERROR 2025-08-12 19:21:38,997 basehttp 23698 140232865343168 "GET /dashboard/user/ HTTP/1.1" 500 188396
WARNING 2025-08-12 19:21:39,290 log 23698 140232865343168 Not Found: /favicon.ico
ERROR 2025-08-12 19:22:15,039 log 23698 140232865343168 Internal Server Error: /dashboard/user/
Traceback (most recent call last):
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codex/oapi_canteen/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'profile' not found. 'profile' is not a valid view function or pattern name.
ERROR 2025-08-12 19:22:15,048 basehttp 23698 140232865343168 "GET /dashboard/user/ HTTP/1.1" 500 188432
